### ISSUE TITLE
I made a mistake while compiling the UI package

### ISSUE THREAD

**Issue by zhyb86** [a1k0n/autorustler#1]
/home/pi/autorustler/ui/imu.cc: In function ‘void* IMUThread(void*)’:
/home/pi/autorustler/ui/imu.cc:16:7: error: no matching function for call to ‘IMU::IMU()’   
IMU imu;       
    ^
/home/pi/autorustler/ui/imu.cc:16:7: note: candidates are:In file included from /home/pi/autorustler/ui/imu.cc:8:0:/home/pi/autorustler/imu/imu.h:25:12: note: IMU::IMU(const I2C&)   
explicit IMU(const I2C &i2c) : i2c_(i2c), YTY_(10, 10) {}            
         ^
/home/pi/autorustler/imu/imu.h:25:12: note:   candidate expects 1 argument, 0 provided
/home/pi/autorustler/imu/imu.h:23:7: note: IMU::IMU(const IMU&) 
class IMU {       
      ^
/home/pi/autorustler/imu/imu.h:23:7: note:   candidate expects 1 argument, 0 provided
/home/pi/autorustler/ui/imu.cc:17:22: error: no matching function for call to ‘IMU::Init(int&)’   
if (!imu.Init(i2cfd)) {                      
                   ^
/home/pi/autorustler/ui/imu.cc:17:22: note: candidate is:In file included from /home/pi/autorustler/ui/imu.cc:8:0:/home/pi/autorustler/imu/imu.h:27:8: note: bool IMU::Init()   
bool Init();        
     ^
/home/pi/autorustler/imu/imu.h:27:8: note:   candidate expects 0 arguments, 1 provided
/home/pi/autorustler/ui/imu.cc:23:11: error: ‘class RadioControl’ has no member named ‘Init’   
if (!rc.Init()) {           
        ^
/home/pi/autorustler/ui/imu.cc:37:14: error: ‘class IMU’ has no member named ‘ReadRaw’     
if (!imu.ReadRaw(&s)) {              
         ^
/home/pi/autorustler/ui/imu.cc:41:9: error: ‘class IMU’ has no member named ‘Calibrate’     
imu.Calibrate(s, &uistate.imu_state);         
    ^
ui/CMakeFiles/ui.dir/build.make:134: recipe for target 'ui/CMakeFiles/ui.dir/imu.cc.o' faile
dmake[2]: *** [ui/CMakeFiles/ui.dir/imu.cc.o] Error 1
CMakeFiles/Makefile2:5449: recipe for target 'ui/CMakeFiles/ui.dir/all' failed
make[1]: *** [ui/CMakeFiles/ui.dir/all] Error 2
Makefile:149: recipe for target 'all' 
failedmake: *** [all] Error 2

**Comment by a1k0n** [comment]
Sorry, the UI package is dead code from several iterations ago. I might as well just remove it.

**Comment by a1k0n** [comment]
I haven't done a good job of documenting anything in here, really... "drive" is the main program now; it's controlled with a bluetooth controller and has no display.
